services:
  gateway-service:
    build: ./backend/gateway-service
    image: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      AUTH_ISSUER_URL: http://auth-service:8081
      EUREKA_URL: http://discovery-serivce:8761
    depends_on:
      auth-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: "curl --fail localhost:8080/actuator/health"
      interval: 20s
      timeout: 1s
      retries: 5
      start_period: 30s

  auth-service:
    build: ./backend/auth-service
    image: auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://database:5432
      DB_AUTH_DATABASE: ${DB_AUTH_DATABASE}
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      EUREKA_URL: http://discovery-service:8761
    depends_on:
      discovery-service:
        condition: service_healthy
      database:
        condition: service_healthy
    healthcheck:
      test: "curl --fail localhost:8081/actuator/health"
      interval: 20s
      timeout: 1s
      retries: 5
      start_period: 30s

  discovery-service:
    build: ./backend/discovery-service
    image: discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail localhost:8761/actuator/health"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_AUTH_DATABASE}:${DB_AUTH_USERNAME}, ${DB_API_DATABASE}:${DB_API_USERNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infra/script/db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8.2-alpine
    container_name: cache
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
  pg-data: