services:
  gateway-service:
    build: ./backend/gateway-service
    image: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      AUTH_ISSUER_URI: ${AUTH_ISSUER_URI:http://localhost:8081}
    depends_on:
      auth-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 15s
      retries: 3

  auth-service:
    build: ./backend/auth-service
    image: auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${DB_URL}
      DB_AUTH_DATABASE: ${DB_AUTH_DATABASE}
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 1m
      timeout: 15s
      retries: 3

  discovery-service:
    build: ./backend/discovery-service
    image: discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 1m
      timeout: 15s
      retries: 3

  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_AUTH_DATABASE}:${DB_AUTH_USERNAME}, ${DB_API_DATABASE}:${DB_API_USERNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infra/script/db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

  cache:
    image: redis:8.2-alpine
    container_name: cache
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  pg-data: