spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}/${DB_AUTH_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${DB_AUTH_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka

server:
  port: 8081

oauth2:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  client_registration_id: "auth-server"