spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: CLIENTSESSION
      timeout: 30m

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka

oauth2:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  issuer_uri: ${AUTH_ISSUER_URL}
  client-registration-id: "auth-server"

logging:
  level:
    org.springframework.security.oauth2: TRACE
    org.springframework.security: TRACE
    org.springframework.data.redis: TRACE
    org.springframework.cloud: TRACE