name: auth-ci.yml
on:
  push:
    branches:
      - main
    path:
      - 'backend/auth-service/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/auth-service/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'corretto'
          cache: 'maven'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build Application
        run: |
          cd ./backend/auth-service
          mvn clean package -DskipTests

  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'corretto'
          cache: 'maven'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Run tests
        run: |
          cd ./backend/auth-service
          mvn clean test -Deureka.client.enabled=false

  build-image:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    name: Build Docker Image
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: backend/auth-service
          platforms: linux/amd64
          push: true
          file: backend/auth-service/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/sales-predictions-auth-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sales-predictions-auth-service:latest